#!/bin/sh -e
echo "\x1b[37;1mSetup devel...\x1b[0m\n"

#
# Check for Bundle
#
if [ ! $(which bundle) ]; then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
else
  echo "  + Bundler found."
fi

#
# Check for Npm
#
if [ ! $(which npm) ]; then
  echo "  x You need to install Node/Npm:"
  echo "    nodebrew install v0.12.x"
else
  echo "  + Npm found."
fi

#
# Check for Bower
#
if [ ! $(which bower) ]; then
  echo "  x You need to install Bower:"
  echo "    npm install -g bower"
else
  echo "  + Bower found."
fi

#
# Check for PostgreSQL
#
if ! psql -l | fgrep -q postgres; then
  echo "  x You need to setup PostgreSQL"
  echo "    brew install postgresql93"
  echo "    or/ brew info postgresql93"
else
  echo "  + PostgreSQL found."
fi

#
# Check for config/secrets.yml
#
if [ ! -f ./config/secrets.yml ]; then
  echo "  x You need to add config/secrets.yml"
  echo "    ./bin/rake secret"
  echo "    vi config/secrets.yml"
else
  echo "  + config/secrets.yml found."
fi


echo "\n\x1b[34;1m==> \x1b[0m\x1b[37;1mInstalling\x1b[0m"

echo "  + Install ruby gems"
bundle install --path vendor/bundle --binstubs vendor/bundle/bin --without production --jobs=2 --retry=3 --quiet

echo "  + Install bower components"
bower install

echo "  + Create PostgreSQL databases"
if ! psql -l | fgrep -q knock_on_development; then
  ./bin/bundle exec rake db:create
fi
# ./bin/bundle exec rake db:reset


echo "\n\x1b[34;1m==> \x1b[0m\x1b[37;1mCaveats\x1b[0m"
echo "To use dotenv create .env and write:"
echo "  'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET' for OmniAuth Google OAuth2"

echo "\nTo use direnv create .envrc and write:"
echo "  PATH_add vendor/bundle/bin"
echo "  export PATH=\$PWD/bin:\$PATH"

echo "\nCongrats!"
